-- AlterTable
ALTER TABLE `project` ADD COLUMN `budget_trend` ENUM('INCREASING', 'STABLE', 'DECREASING') NOT NULL DEFAULT 'STABLE',
    ADD COLUMN `schedule_trend` ENUM('INCREASING', 'STABLE', 'DECREASING') NOT NULL DEFAULT 'STABLE';
